name: Hiba/bug
description: Az alkalmazásban talált probléma jelentése
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Mi történt?
      description: Mondd el azt is, hogy mire számítottál? Ha segíthet, képeket is fel tudsz tölteni ide. 
      placeholder: Mondd el, hogy mit látsz!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operációs rendszer
      description: Milyen eszközön találtad a probémát?
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Verzió
      description: "A profil odalon található verzió"
      placeholder: "pl. v1.11.2 (42)"
