name: Funkció kérés
description: Ossz meg egy ötletet
labels: [enhancement]
body:
  - type: textarea
    id: feature
    attributes:
      label: "A funkció/ötlet leírása:"
    validations:
      required: true
